image: demers/python420w4a

stages:
  - test


utests:
  stage: test
  script:
    - pip3 install -r requirements.txt
    - python3 -m unittest discover -s project -v -p test_*.py

dtests:
  variables:
    $CI_BUILDS_DIR = "/mnt/data/files"
  stage: test
  script:
    - pip3 install -r requirements.txt
    - ./run.sh ./project/myAPI/api.py &
    - python3 -m unittest discover -s project -v -p dtest_*.py
